#!/bin/bash

echo 'Starting batch 1/6'
python run_coordinate_descent.py 0003 &
python run_coordinate_descent.py 0004 &
python run_coordinate_descent.py 0005 &
python run_coordinate_descent.py 0006 &
python run_coordinate_descent.py 0007 &
python run_coordinate_descent.py 0008 &
python run_coordinate_descent.py 0010 &
python run_coordinate_descent.py 0011 &
python run_coordinate_descent.py 0012 &
python run_coordinate_descent.py 0013 &
python run_coordinate_descent.py 0019 &
python run_coordinate_descent.py 0020 &
python run_coordinate_descent.py 0022 &
python run_coordinate_descent.py 0023 &
python run_coordinate_descent.py 0024 &
python run_coordinate_descent.py 0025 &
python run_coordinate_descent.py 0026 &
python run_coordinate_descent.py 0027 &
python run_coordinate_descent.py 0044 &
python run_coordinate_descent.py 0045 &
python run_coordinate_descent.py 0048 &
python run_coordinate_descent.py 0049 &
python run_coordinate_descent.py 0050 &
python run_coordinate_descent.py 0051 &
python run_coordinate_descent.py 0052 &
python run_coordinate_descent.py 0053 &
python run_coordinate_descent.py 0054 &
python run_coordinate_descent.py 0055 &
python run_coordinate_descent.py 0058 &
python run_coordinate_descent.py 0064 &
python run_coordinate_descent.py 0065 &
python run_coordinate_descent.py 0066 &
python run_coordinate_descent.py 0067 &
python run_coordinate_descent.py 0068 &
python run_coordinate_descent.py 0069 &
python run_coordinate_descent.py 0070 &
python run_coordinate_descent.py 0071 &
python run_coordinate_descent.py 0072 &
python run_coordinate_descent.py 0073 &
python run_coordinate_descent.py 0074 &
python run_coordinate_descent.py 0075 &
python run_coordinate_descent.py 0080 &
python run_coordinate_descent.py 0081 &
python run_coordinate_descent.py 0082 &
python run_coordinate_descent.py 0083 &
python run_coordinate_descent.py 0092 &
python run_coordinate_descent.py 0093 &
python run_coordinate_descent.py 0094 &
python run_coordinate_descent.py 0095 &
python run_coordinate_descent.py 0096 &
python run_coordinate_descent.py 0097 &
python run_coordinate_descent.py 0098 &
python run_coordinate_descent.py 0099 &
python run_coordinate_descent.py 0100 &
python run_coordinate_descent.py 0101 &
python run_coordinate_descent.py 0102 &
python run_coordinate_descent.py 0103 &
python run_coordinate_descent.py 0104 &
python run_coordinate_descent.py 0105 &
python run_coordinate_descent.py 0106 &
python run_coordinate_descent.py 0107 &
python run_coordinate_descent.py 0108 &
python run_coordinate_descent.py 0109 &
python run_coordinate_descent.py 0110 &
python run_coordinate_descent.py 0111 &
python run_coordinate_descent.py 0112 &
python run_coordinate_descent.py 0113 &
python run_coordinate_descent.py 0114 &
python run_coordinate_descent.py 0115 &
python run_coordinate_descent.py 0116 &
python run_coordinate_descent.py 0120 &
python run_coordinate_descent.py 0121 &
python run_coordinate_descent.py 0122 &
python run_coordinate_descent.py 0123 &
python run_coordinate_descent.py 0124 &
python run_coordinate_descent.py 0130 &
python run_coordinate_descent.py 0135 &
python run_coordinate_descent.py 0136 &
python run_coordinate_descent.py 0138 &
python run_coordinate_descent.py 0139 &
python run_coordinate_descent.py 0140 &
python run_coordinate_descent.py 0141 &
python run_coordinate_descent.py 0142 &
python run_coordinate_descent.py 0143 &
python run_coordinate_descent.py 0144 &
python run_coordinate_descent.py 0145 &
python run_coordinate_descent.py 0146 &
python run_coordinate_descent.py 0147 &
python run_coordinate_descent.py 0148 &
python run_coordinate_descent.py 0149 &
python run_coordinate_descent.py 0150 &
python run_coordinate_descent.py 0151 &
python run_coordinate_descent.py 0152 &
python run_coordinate_descent.py 0156 &
python run_coordinate_descent.py 0157 &
python run_coordinate_descent.py 0158 &
python run_coordinate_descent.py 0159 &
python run_coordinate_descent.py 0160 &
python run_coordinate_descent.py 0161 &
python run_coordinate_descent.py 0162 &
python run_coordinate_descent.py 0163 &
python run_coordinate_descent.py 0164 &
python run_coordinate_descent.py 0165 &
python run_coordinate_descent.py 0166 &
python run_coordinate_descent.py 0170 &
python run_coordinate_descent.py 0177 &
python run_coordinate_descent.py 0178 &
python run_coordinate_descent.py 0179 &
python run_coordinate_descent.py 0203 &
python run_coordinate_descent.py 0204 &
python run_coordinate_descent.py 0205 &
python run_coordinate_descent.py 0206 &
python run_coordinate_descent.py 0213 &
python run_coordinate_descent.py 0214 &
python run_coordinate_descent.py 0215 &
python run_coordinate_descent.py 0216 &
python run_coordinate_descent.py 0217 &
python run_coordinate_descent.py 0218 &
python run_coordinate_descent.py 0219 &
python run_coordinate_descent.py 0223 &
python run_coordinate_descent.py 0224 &
python run_coordinate_descent.py 0225 &
python run_coordinate_descent.py 0226 &
python run_coordinate_descent.py 0227 &
python run_coordinate_descent.py 0228 &
python run_coordinate_descent.py 0229 &
python run_coordinate_descent.py 0230 &
python run_coordinate_descent.py 0231 &
python run_coordinate_descent.py 0232 &
python run_coordinate_descent.py 0233 &
python run_coordinate_descent.py 0234 &
python run_coordinate_descent.py 0235 &
python run_coordinate_descent.py 0236 &
python run_coordinate_descent.py 0237 &
python run_coordinate_descent.py 0238 &
python run_coordinate_descent.py 0239 &
python run_coordinate_descent.py 0240 &
python run_coordinate_descent.py 0241 &
python run_coordinate_descent.py 0242 &
python run_coordinate_descent.py 0243 &
python run_coordinate_descent.py 0244 &
python run_coordinate_descent.py 0245 &
python run_coordinate_descent.py 0246 &
python run_coordinate_descent.py 0247 &
wait

echo 'Starting batch 2/6'
python run_coordinate_descent.py 0248 &
python run_coordinate_descent.py 0249 &
python run_coordinate_descent.py 0251 &
python run_coordinate_descent.py 0252 &
python run_coordinate_descent.py 0253 &
python run_coordinate_descent.py 0254 &
python run_coordinate_descent.py 0255 &
python run_coordinate_descent.py 0256 &
python run_coordinate_descent.py 0257 &
python run_coordinate_descent.py 0258 &
python run_coordinate_descent.py 0259 &
python run_coordinate_descent.py 0260 &
python run_coordinate_descent.py 0261 &
python run_coordinate_descent.py 0262 &
python run_coordinate_descent.py 0263 &
python run_coordinate_descent.py 0265 &
python run_coordinate_descent.py 0266 &
python run_coordinate_descent.py 0267 &
python run_coordinate_descent.py 0268 &
python run_coordinate_descent.py 0269 &
python run_coordinate_descent.py 0270 &
python run_coordinate_descent.py 0274 &
python run_coordinate_descent.py 0275 &
python run_coordinate_descent.py 0276 &
python run_coordinate_descent.py 0277 &
python run_coordinate_descent.py 0278 &
python run_coordinate_descent.py 0286 &
python run_coordinate_descent.py 0287 &
python run_coordinate_descent.py 0288 &
python run_coordinate_descent.py 0289 &
python run_coordinate_descent.py 0290 &
python run_coordinate_descent.py 0291 &
python run_coordinate_descent.py 0292 &
python run_coordinate_descent.py 0293 &
python run_coordinate_descent.py 0294 &
python run_coordinate_descent.py 0295 &
python run_coordinate_descent.py 0303 &
python run_coordinate_descent.py 0304 &
python run_coordinate_descent.py 0305 &
python run_coordinate_descent.py 0306 &
python run_coordinate_descent.py 0307 &
python run_coordinate_descent.py 0308 &
python run_coordinate_descent.py 0309 &
python run_coordinate_descent.py 0313 &
python run_coordinate_descent.py 0314 &
python run_coordinate_descent.py 0318 &
python run_coordinate_descent.py 0319 &
python run_coordinate_descent.py 0320 &
python run_coordinate_descent.py 0321 &
python run_coordinate_descent.py 0322 &
python run_coordinate_descent.py 0323 &
python run_coordinate_descent.py 0324 &
python run_coordinate_descent.py 0336 &
python run_coordinate_descent.py 0337 &
python run_coordinate_descent.py 0338 &
python run_coordinate_descent.py 0339 &
python run_coordinate_descent.py 0340 &
python run_coordinate_descent.py 0341 &
python run_coordinate_descent.py 0342 &
python run_coordinate_descent.py 0343 &
python run_coordinate_descent.py 0344 &
python run_coordinate_descent.py 0345 &
python run_coordinate_descent.py 0346 &
python run_coordinate_descent.py 0347 &
python run_coordinate_descent.py 0348 &
python run_coordinate_descent.py 0349 &
python run_coordinate_descent.py 0350 &
python run_coordinate_descent.py 0353 &
python run_coordinate_descent.py 0354 &
python run_coordinate_descent.py 0365 &
python run_coordinate_descent.py 0366 &
python run_coordinate_descent.py 0367 &
python run_coordinate_descent.py 0368 &
python run_coordinate_descent.py 0369 &
python run_coordinate_descent.py 0370 &
python run_coordinate_descent.py 0371 &
python run_coordinate_descent.py 0372 &
python run_coordinate_descent.py 0373 &
python run_coordinate_descent.py 0374 &
python run_coordinate_descent.py 0375 &
python run_coordinate_descent.py 0376 &
python run_coordinate_descent.py 0377 &
python run_coordinate_descent.py 0378 &
python run_coordinate_descent.py 0379 &
python run_coordinate_descent.py 0380 &
python run_coordinate_descent.py 0381 &
python run_coordinate_descent.py 0382 &
python run_coordinate_descent.py 0383 &
python run_coordinate_descent.py 0391 &
python run_coordinate_descent.py 0392 &
python run_coordinate_descent.py 0393 &
python run_coordinate_descent.py 0394 &
python run_coordinate_descent.py 0398 &
python run_coordinate_descent.py 0399 &
python run_coordinate_descent.py 0400 &
python run_coordinate_descent.py 0401 &
python run_coordinate_descent.py 0402 &
python run_coordinate_descent.py 0403 &
python run_coordinate_descent.py 0404 &
python run_coordinate_descent.py 0405 &
python run_coordinate_descent.py 0406 &
python run_coordinate_descent.py 0407 &
python run_coordinate_descent.py 0408 &
python run_coordinate_descent.py 0409 &
python run_coordinate_descent.py 0410 &
python run_coordinate_descent.py 0415 &
python run_coordinate_descent.py 0416 &
python run_coordinate_descent.py 0417 &
python run_coordinate_descent.py 0418 &
python run_coordinate_descent.py 0419 &
python run_coordinate_descent.py 0420 &
python run_coordinate_descent.py 0421 &
python run_coordinate_descent.py 0422 &
python run_coordinate_descent.py 0423 &
python run_coordinate_descent.py 0424 &
python run_coordinate_descent.py 0425 &
python run_coordinate_descent.py 0426 &
python run_coordinate_descent.py 0427 &
python run_coordinate_descent.py 0428 &
python run_coordinate_descent.py 0429 &
python run_coordinate_descent.py 0436 &
python run_coordinate_descent.py 0437 &
python run_coordinate_descent.py 0438 &
python run_coordinate_descent.py 0439 &
python run_coordinate_descent.py 0440 &
python run_coordinate_descent.py 0449 &
python run_coordinate_descent.py 0450 &
python run_coordinate_descent.py 0451 &
python run_coordinate_descent.py 0452 &
python run_coordinate_descent.py 0453 &
python run_coordinate_descent.py 0454 &
python run_coordinate_descent.py 0455 &
python run_coordinate_descent.py 0456 &
python run_coordinate_descent.py 0457 &
python run_coordinate_descent.py 0458 &
python run_coordinate_descent.py 0459 &
python run_coordinate_descent.py 0460 &
python run_coordinate_descent.py 0461 &
python run_coordinate_descent.py 0467 &
python run_coordinate_descent.py 0468 &
python run_coordinate_descent.py 0478 &
python run_coordinate_descent.py 0479 &
python run_coordinate_descent.py 0480 &
python run_coordinate_descent.py 0481 &
wait

echo 'Starting batch 3/6'
python run_coordinate_descent.py 0482 &
python run_coordinate_descent.py 0483 &
python run_coordinate_descent.py 0484 &
python run_coordinate_descent.py 0485 &
python run_coordinate_descent.py 0486 &
python run_coordinate_descent.py 0487 &
python run_coordinate_descent.py 0488 &
python run_coordinate_descent.py 0489 &
python run_coordinate_descent.py 0490 &
python run_coordinate_descent.py 0491 &
python run_coordinate_descent.py 0492 &
python run_coordinate_descent.py 0493 &
python run_coordinate_descent.py 0494 &
python run_coordinate_descent.py 0495 &
python run_coordinate_descent.py 0496 &
python run_coordinate_descent.py 0497 &
python run_coordinate_descent.py 0498 &
python run_coordinate_descent.py 0499 &
python run_coordinate_descent.py 0500 &
python run_coordinate_descent.py 0501 &
python run_coordinate_descent.py 0502 &
python run_coordinate_descent.py 0503 &
python run_coordinate_descent.py 0504 &
python run_coordinate_descent.py 0505 &
python run_coordinate_descent.py 0506 &
python run_coordinate_descent.py 0507 &
python run_coordinate_descent.py 0514 &
python run_coordinate_descent.py 0527 &
python run_coordinate_descent.py 0528 &
python run_coordinate_descent.py 0529 &
python run_coordinate_descent.py 0530 &
python run_coordinate_descent.py 0534 &
python run_coordinate_descent.py 0535 &
python run_coordinate_descent.py 0536 &
python run_coordinate_descent.py 0540 &
python run_coordinate_descent.py 0541 &
python run_coordinate_descent.py 0542 &
python run_coordinate_descent.py 0543 &
python run_coordinate_descent.py 0544 &
python run_coordinate_descent.py 0545 &
python run_coordinate_descent.py 0546 &
python run_coordinate_descent.py 0547 &
python run_coordinate_descent.py 0548 &
python run_coordinate_descent.py 0552 &
python run_coordinate_descent.py 0553 &
python run_coordinate_descent.py 0554 &
python run_coordinate_descent.py 0572 &
python run_coordinate_descent.py 0573 &
python run_coordinate_descent.py 0574 &
python run_coordinate_descent.py 0575 &
python run_coordinate_descent.py 0576 &
python run_coordinate_descent.py 0577 &
python run_coordinate_descent.py 0578 &
python run_coordinate_descent.py 0584 &
python run_coordinate_descent.py 0585 &
python run_coordinate_descent.py 0586 &
python run_coordinate_descent.py 0587 &
python run_coordinate_descent.py 0588 &
python run_coordinate_descent.py 0589 &
python run_coordinate_descent.py 0590 &
python run_coordinate_descent.py 0595 &
python run_coordinate_descent.py 0596 &
python run_coordinate_descent.py 0597 &
python run_coordinate_descent.py 0598 &
python run_coordinate_descent.py 0599 &
python run_coordinate_descent.py 0600 &
python run_coordinate_descent.py 0601 &
python run_coordinate_descent.py 0602 &
python run_coordinate_descent.py 0608 &
python run_coordinate_descent.py 0609 &
python run_coordinate_descent.py 0610 &
python run_coordinate_descent.py 0611 &
python run_coordinate_descent.py 0614 &
python run_coordinate_descent.py 0615 &
python run_coordinate_descent.py 0616 &
python run_coordinate_descent.py 0622 &
python run_coordinate_descent.py 0623 &
python run_coordinate_descent.py 0624 &
python run_coordinate_descent.py 0625 &
python run_coordinate_descent.py 0626 &
python run_coordinate_descent.py 0627 &
python run_coordinate_descent.py 0628 &
python run_coordinate_descent.py 0629 &
python run_coordinate_descent.py 0630 &
python run_coordinate_descent.py 0631 &
python run_coordinate_descent.py 0632 &
python run_coordinate_descent.py 0639 &
python run_coordinate_descent.py 0640 &
python run_coordinate_descent.py 0641 &
python run_coordinate_descent.py 0642 &
python run_coordinate_descent.py 0643 &
python run_coordinate_descent.py 0646 &
python run_coordinate_descent.py 0647 &
python run_coordinate_descent.py 0648 &
python run_coordinate_descent.py 0649 &
python run_coordinate_descent.py 0652 &
python run_coordinate_descent.py 0653 &
python run_coordinate_descent.py 0654 &
python run_coordinate_descent.py 0655 &
python run_coordinate_descent.py 0659 &
python run_coordinate_descent.py 0660 &
python run_coordinate_descent.py 0661 &
python run_coordinate_descent.py 0662 &
python run_coordinate_descent.py 0665 &
python run_coordinate_descent.py 0666 &
python run_coordinate_descent.py 0667 &
python run_coordinate_descent.py 0674 &
python run_coordinate_descent.py 0675 &
python run_coordinate_descent.py 0682 &
python run_coordinate_descent.py 0683 &
python run_coordinate_descent.py 0684 &
python run_coordinate_descent.py 0685 &
python run_coordinate_descent.py 0691 &
python run_coordinate_descent.py 0692 &
python run_coordinate_descent.py 0695 &
python run_coordinate_descent.py 0696 &
python run_coordinate_descent.py 0700 &
python run_coordinate_descent.py 0701 &
python run_coordinate_descent.py 0702 &
python run_coordinate_descent.py 0703 &
python run_coordinate_descent.py 0704 &
python run_coordinate_descent.py 0705 &
python run_coordinate_descent.py 0714 &
python run_coordinate_descent.py 0715 &
python run_coordinate_descent.py 0716 &
python run_coordinate_descent.py 0719 &
python run_coordinate_descent.py 0720 &
python run_coordinate_descent.py 0721 &
python run_coordinate_descent.py 0722 &
python run_coordinate_descent.py 0723 &
python run_coordinate_descent.py 0729 &
python run_coordinate_descent.py 0730 &
python run_coordinate_descent.py 0735 &
python run_coordinate_descent.py 0736 &
python run_coordinate_descent.py 0737 &
python run_coordinate_descent.py 0738 &
python run_coordinate_descent.py 0739 &
python run_coordinate_descent.py 0740 &
python run_coordinate_descent.py 0741 &
python run_coordinate_descent.py 0742 &
python run_coordinate_descent.py 0745 &
python run_coordinate_descent.py 0746 &
python run_coordinate_descent.py 0747 &
python run_coordinate_descent.py 0748 &
wait

echo 'Starting batch 4/6'
python run_coordinate_descent.py 0749 &
python run_coordinate_descent.py 0750 &
python run_coordinate_descent.py 0751 &
python run_coordinate_descent.py 0752 &
python run_coordinate_descent.py 0753 &
python run_coordinate_descent.py 0754 &
python run_coordinate_descent.py 0755 &
python run_coordinate_descent.py 0756 &
python run_coordinate_descent.py 0757 &
python run_coordinate_descent.py 0758 &
python run_coordinate_descent.py 0788 &
python run_coordinate_descent.py 0789 &
python run_coordinate_descent.py 0790 &
python run_coordinate_descent.py 0791 &
python run_coordinate_descent.py 0792 &
python run_coordinate_descent.py 0793 &
python run_coordinate_descent.py 0794 &
python run_coordinate_descent.py 0795 &
python run_coordinate_descent.py 0796 &
python run_coordinate_descent.py 0797 &
python run_coordinate_descent.py 0798 &
python run_coordinate_descent.py 0799 &
python run_coordinate_descent.py 0805 &
python run_coordinate_descent.py 0806 &
python run_coordinate_descent.py 0807 &
python run_coordinate_descent.py 0808 &
python run_coordinate_descent.py 0809 &
python run_coordinate_descent.py 0815 &
python run_coordinate_descent.py 0816 &
python run_coordinate_descent.py 0817 &
python run_coordinate_descent.py 0818 &
python run_coordinate_descent.py 0819 &
python run_coordinate_descent.py 0820 &
python run_coordinate_descent.py 0824 &
python run_coordinate_descent.py 0825 &
python run_coordinate_descent.py 0826 &
python run_coordinate_descent.py 0827 &
python run_coordinate_descent.py 0828 &
python run_coordinate_descent.py 0829 &
python run_coordinate_descent.py 0830 &
python run_coordinate_descent.py 0831 &
python run_coordinate_descent.py 0832 &
python run_coordinate_descent.py 0847 &
python run_coordinate_descent.py 0848 &
python run_coordinate_descent.py 0849 &
python run_coordinate_descent.py 0853 &
python run_coordinate_descent.py 0854 &
python run_coordinate_descent.py 0855 &
python run_coordinate_descent.py 0856 &
python run_coordinate_descent.py 0863 &
python run_coordinate_descent.py 0864 &
python run_coordinate_descent.py 0865 &
python run_coordinate_descent.py 0866 &
python run_coordinate_descent.py 0867 &
python run_coordinate_descent.py 0868 &
python run_coordinate_descent.py 0872 &
python run_coordinate_descent.py 0873 &
python run_coordinate_descent.py 0874 &
python run_coordinate_descent.py 0875 &
python run_coordinate_descent.py 0876 &
python run_coordinate_descent.py 0877 &
python run_coordinate_descent.py 0878 &
python run_coordinate_descent.py 0879 &
python run_coordinate_descent.py 0880 &
python run_coordinate_descent.py 0881 &
python run_coordinate_descent.py 0882 &
python run_coordinate_descent.py 0883 &
python run_coordinate_descent.py 0884 &
python run_coordinate_descent.py 0885 &
python run_coordinate_descent.py 0886 &
python run_coordinate_descent.py 0887 &
python run_coordinate_descent.py 0888 &
python run_coordinate_descent.py 0889 &
python run_coordinate_descent.py 0890 &
python run_coordinate_descent.py 0891 &
python run_coordinate_descent.py 0892 &
python run_coordinate_descent.py 0893 &
python run_coordinate_descent.py 0894 &
python run_coordinate_descent.py 0895 &
python run_coordinate_descent.py 0896 &
python run_coordinate_descent.py 0897 &
python run_coordinate_descent.py 0898 &
python run_coordinate_descent.py 0899 &
python run_coordinate_descent.py 0900 &
python run_coordinate_descent.py 0901 &
python run_coordinate_descent.py 0902 &
python run_coordinate_descent.py 0903 &
python run_coordinate_descent.py 0904 &
python run_coordinate_descent.py 0905 &
python run_coordinate_descent.py 0909 &
python run_coordinate_descent.py 0910 &
python run_coordinate_descent.py 0911 &
python run_coordinate_descent.py 0912 &
python run_coordinate_descent.py 0913 &
python run_coordinate_descent.py 0914 &
python run_coordinate_descent.py 0915 &
python run_coordinate_descent.py 0916 &
python run_coordinate_descent.py 0920 &
python run_coordinate_descent.py 0921 &
python run_coordinate_descent.py 0922 &
python run_coordinate_descent.py 0923 &
python run_coordinate_descent.py 0924 &
python run_coordinate_descent.py 0925 &
python run_coordinate_descent.py 0929 &
python run_coordinate_descent.py 0930 &
python run_coordinate_descent.py 0931 &
python run_coordinate_descent.py 0936 &
python run_coordinate_descent.py 0937 &
python run_coordinate_descent.py 0938 &
python run_coordinate_descent.py 0939 &
python run_coordinate_descent.py 0940 &
python run_coordinate_descent.py 0941 &
python run_coordinate_descent.py 0942 &
python run_coordinate_descent.py 0943 &
python run_coordinate_descent.py 0944 &
python run_coordinate_descent.py 0948 &
python run_coordinate_descent.py 0949 &
python run_coordinate_descent.py 0950 &
python run_coordinate_descent.py 0951 &
python run_coordinate_descent.py 0952 &
python run_coordinate_descent.py 0953 &
python run_coordinate_descent.py 0954 &
python run_coordinate_descent.py 0955 &
python run_coordinate_descent.py 0956 &
python run_coordinate_descent.py 0957 &
python run_coordinate_descent.py 0958 &
python run_coordinate_descent.py 0963 &
python run_coordinate_descent.py 0964 &
python run_coordinate_descent.py 0968 &
python run_coordinate_descent.py 0969 &
python run_coordinate_descent.py 0978 &
python run_coordinate_descent.py 0979 &
python run_coordinate_descent.py 0980 &
python run_coordinate_descent.py 0981 &
python run_coordinate_descent.py 0982 &
python run_coordinate_descent.py 0983 &
python run_coordinate_descent.py 0984 &
python run_coordinate_descent.py 0985 &
python run_coordinate_descent.py 0986 &
python run_coordinate_descent.py 0987 &
python run_coordinate_descent.py 0988 &
python run_coordinate_descent.py 0989 &
python run_coordinate_descent.py 0990 &
python run_coordinate_descent.py 0996 &
wait

echo 'Starting batch 5/6'
python run_coordinate_descent.py 0997 &
python run_coordinate_descent.py 0998 &
python run_coordinate_descent.py 0999 &
python run_coordinate_descent.py 1000 &
python run_coordinate_descent.py 1005 &
python run_coordinate_descent.py 1006 &
python run_coordinate_descent.py 1007 &
python run_coordinate_descent.py 1008 &
python run_coordinate_descent.py 1009 &
python run_coordinate_descent.py 1013 &
python run_coordinate_descent.py 1014 &
python run_coordinate_descent.py 1015 &
python run_coordinate_descent.py 1016 &
python run_coordinate_descent.py 1017 &
python run_coordinate_descent.py 1018 &
python run_coordinate_descent.py 1019 &
python run_coordinate_descent.py 1020 &
python run_coordinate_descent.py 1024 &
python run_coordinate_descent.py 1025 &
python run_coordinate_descent.py 1026 &
python run_coordinate_descent.py 1027 &
python run_coordinate_descent.py 1028 &
python run_coordinate_descent.py 1029 &
python run_coordinate_descent.py 1030 &
python run_coordinate_descent.py 1031 &
python run_coordinate_descent.py 1035 &
python run_coordinate_descent.py 1036 &
python run_coordinate_descent.py 1037 &
python run_coordinate_descent.py 1040 &
python run_coordinate_descent.py 1041 &
python run_coordinate_descent.py 1042 &
python run_coordinate_descent.py 1043 &
python run_coordinate_descent.py 1044 &
python run_coordinate_descent.py 1045 &
python run_coordinate_descent.py 1046 &
python run_coordinate_descent.py 1047 &
python run_coordinate_descent.py 1050 &
python run_coordinate_descent.py 1051 &
python run_coordinate_descent.py 1054 &
python run_coordinate_descent.py 1055 &
python run_coordinate_descent.py 1056 &
python run_coordinate_descent.py 1059 &
python run_coordinate_descent.py 1060 &
python run_coordinate_descent.py 1061 &
python run_coordinate_descent.py 1062 &
python run_coordinate_descent.py 1063 &
python run_coordinate_descent.py 1064 &
python run_coordinate_descent.py 1065 &
python run_coordinate_descent.py 1066 &
python run_coordinate_descent.py 1067 &
python run_coordinate_descent.py 1068 &
python run_coordinate_descent.py 1069 &
python run_coordinate_descent.py 1070 &
python run_coordinate_descent.py 1071 &
python run_coordinate_descent.py 1072 &
python run_coordinate_descent.py 1073 &
python run_coordinate_descent.py 1074 &
python run_coordinate_descent.py 1085 &
python run_coordinate_descent.py 1086 &
python run_coordinate_descent.py 1087 &
python run_coordinate_descent.py 1097 &
python run_coordinate_descent.py 1105 &
python run_coordinate_descent.py 1110 &
python run_coordinate_descent.py 1111 &
python run_coordinate_descent.py 1112 &
python run_coordinate_descent.py 1113 &
python run_coordinate_descent.py 1114 &
python run_coordinate_descent.py 1115 &
python run_coordinate_descent.py 1116 &
python run_coordinate_descent.py 1120 &
python run_coordinate_descent.py 1121 &
python run_coordinate_descent.py 1122 &
python run_coordinate_descent.py 1132 &
python run_coordinate_descent.py 1133 &
python run_coordinate_descent.py 1134 &
python run_coordinate_descent.py 1137 &
python run_coordinate_descent.py 1138 &
python run_coordinate_descent.py 1139 &
python run_coordinate_descent.py 1140 &
python run_coordinate_descent.py 1141 &
python run_coordinate_descent.py 1142 &
python run_coordinate_descent.py 1143 &
python run_coordinate_descent.py 1159 &
python run_coordinate_descent.py 1160 &
python run_coordinate_descent.py 1161 &
python run_coordinate_descent.py 1168 &
python run_coordinate_descent.py 1169 &
python run_coordinate_descent.py 1172 &
python run_coordinate_descent.py 1173 &
python run_coordinate_descent.py 1177 &
python run_coordinate_descent.py 1178 &
python run_coordinate_descent.py 1185 &
python run_coordinate_descent.py 1186 &
python run_coordinate_descent.py 1187 &
python run_coordinate_descent.py 1188 &
python run_coordinate_descent.py 1189 &
python run_coordinate_descent.py 1190 &
python run_coordinate_descent.py 1191 &
python run_coordinate_descent.py 1197 &
python run_coordinate_descent.py 1198 &
python run_coordinate_descent.py 1199 &
python run_coordinate_descent.py 1200 &
python run_coordinate_descent.py 1213 &
python run_coordinate_descent.py 1214 &
python run_coordinate_descent.py 1215 &
python run_coordinate_descent.py 1221 &
python run_coordinate_descent.py 1222 &
python run_coordinate_descent.py 1223 &
python run_coordinate_descent.py 1224 &
python run_coordinate_descent.py 1225 &
python run_coordinate_descent.py 1231 &
python run_coordinate_descent.py 1232 &
python run_coordinate_descent.py 1236 &
python run_coordinate_descent.py 1237 &
python run_coordinate_descent.py 1238 &
python run_coordinate_descent.py 1239 &
python run_coordinate_descent.py 1240 &
python run_coordinate_descent.py 1241 &
python run_coordinate_descent.py 1242 &
python run_coordinate_descent.py 1243 &
python run_coordinate_descent.py 1244 &
python run_coordinate_descent.py 1245 &
python run_coordinate_descent.py 1246 &
python run_coordinate_descent.py 1251 &
python run_coordinate_descent.py 1252 &
python run_coordinate_descent.py 1253 &
python run_coordinate_descent.py 1266 &
python run_coordinate_descent.py 1267 &
python run_coordinate_descent.py 1268 &
python run_coordinate_descent.py 1269 &
python run_coordinate_descent.py 1270 &
python run_coordinate_descent.py 1271 &
python run_coordinate_descent.py 1272 &
python run_coordinate_descent.py 1273 &
python run_coordinate_descent.py 1274 &
python run_coordinate_descent.py 1281 &
python run_coordinate_descent.py 1282 &
python run_coordinate_descent.py 1283 &
python run_coordinate_descent.py 1284 &
python run_coordinate_descent.py 1296 &
python run_coordinate_descent.py 1300 &
python run_coordinate_descent.py 1301 &
python run_coordinate_descent.py 1309 &
python run_coordinate_descent.py 1310 &
wait

echo 'Starting batch 6/6'
python run_coordinate_descent.py 1311 &
python run_coordinate_descent.py 1312 &
python run_coordinate_descent.py 1313 &
python run_coordinate_descent.py 1316 &
python run_coordinate_descent.py 1317 &
python run_coordinate_descent.py 1318 &
python run_coordinate_descent.py 1319 &
python run_coordinate_descent.py 1320 &
python run_coordinate_descent.py 1321 &
python run_coordinate_descent.py 1322 &
python run_coordinate_descent.py 1323 &
python run_coordinate_descent.py 1324 &
python run_coordinate_descent.py 1325 &
python run_coordinate_descent.py 1326 &
python run_coordinate_descent.py 1327 &
python run_coordinate_descent.py 1328 &
python run_coordinate_descent.py 1333 &
python run_coordinate_descent.py 1334 &
python run_coordinate_descent.py 1341 &
python run_coordinate_descent.py 1342 &
python run_coordinate_descent.py 1343 &
python run_coordinate_descent.py 1344 &
python run_coordinate_descent.py 1345 &
python run_coordinate_descent.py 1346 &
python run_coordinate_descent.py 1350 &
python run_coordinate_descent.py 1351 &
python run_coordinate_descent.py 1352 &
python run_coordinate_descent.py 1357 &
python run_coordinate_descent.py 1358 &
python run_coordinate_descent.py 1359 &
python run_coordinate_descent.py 1360 &
python run_coordinate_descent.py 1361 &
python run_coordinate_descent.py 1362 &
python run_coordinate_descent.py 1363 &
python run_coordinate_descent.py 1366 &
python run_coordinate_descent.py 1367 &
python run_coordinate_descent.py 1370 &
python run_coordinate_descent.py 1371 &
python run_coordinate_descent.py 1372 &
python run_coordinate_descent.py 1373 &
python run_coordinate_descent.py 1374 &
python run_coordinate_descent.py 1375 &
python run_coordinate_descent.py 1376 &
python run_coordinate_descent.py 1377 &
python run_coordinate_descent.py 1378 &
python run_coordinate_descent.py 1379 &
python run_coordinate_descent.py 1380 &
python run_coordinate_descent.py 1381 &
python run_coordinate_descent.py 1382 &
python run_coordinate_descent.py 1383 &
python run_coordinate_descent.py 1392 &
python run_coordinate_descent.py 1393 &
python run_coordinate_descent.py 1402 &
python run_coordinate_descent.py 1403 &
python run_coordinate_descent.py 1404 &
python run_coordinate_descent.py 1405 &
python run_coordinate_descent.py 1406 &
python run_coordinate_descent.py 1415 &
python run_coordinate_descent.py 1416 &
python run_coordinate_descent.py 1417 &
python run_coordinate_descent.py 1418 &
python run_coordinate_descent.py 1419 &
python run_coordinate_descent.py 1420 &
python run_coordinate_descent.py 1425 &
python run_coordinate_descent.py 1426 &
python run_coordinate_descent.py 1427 &
python run_coordinate_descent.py 1428 &
python run_coordinate_descent.py 1429 &
python run_coordinate_descent.py 1434 &
python run_coordinate_descent.py 1435 &
python run_coordinate_descent.py 1436 &
python run_coordinate_descent.py 1437 &
python run_coordinate_descent.py 1438 &
python run_coordinate_descent.py 1439 &
python run_coordinate_descent.py 1440 &
wait

